spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://localhost:3306/yupi_center?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
#    设置session的过期时间（1天）
  session:
    timeout: 86400


server:
  port: 8081


